{% set name = "wagtail-app-pages" %}
{% set version = "0.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wagtail_app_pages-{{ version }}.tar.gz
  sha256: 407d8a79cedf04e08fdb71151561252881b66c7b7ff167ec29d0a59143285782

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - wagtail >=5.0,<5.3

test:
  imports:
    - wagtail_app_pages
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mwesterhof/wagtail_app_pages
  summary: Full MVC support for wagtail pages
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
